language: php

php:
    - "7.1"


before_script:
    - make install


script:
    - make test



# notifications:
#     irc: "irc.freenode.org#dbwebb"
#     urls:
#       - https://webhooks.gitter.im/e/6e4660b0024de67de0af
#     on_success: change  # options: [always|never|change] default: always
#     on_failure: always  # options: [always|never|change] default: always
#     on_start: never     # options: [always|never|change] default: always
